### ISSUE TITLE
Prefixes on success/error/info messages or not?

### ISSUE THREAD

**Issue by mathias-github** [mc-server/WorldEdit#75]
Should we use prefixes on success/error/info messages, like Core and Essentials does, or should we make the plugin as similar to Bukkit's WorldEdit as possible, and use the current pink and red messages? What do you think?

**Comment by NiLSPACE** [comment]
Well, I'm trying to make it look as much as the bukkit version of WorldEdit so that people have a familiar feeling when using it, so I want the pink/red messages.

Also, I **really** don't like the succes/error/info messages, and I still have no idea why we even implemented it.

**Comment by mathias-github** [comment]
Okay, thank you for the answer and explanation.

What is wrong with the success/error/info messages? Is it the style, are they unnecessary, or something else?

**Comment by NiLSPACE** [comment]
I think the prefixes really clutter up the screen, and since MCServer has so many things to configure not many people will notice that you can disable the prefixes. 

I think a simple `SendMessage` function was enough. If you make the color red, then it's already obvious for me that something is wrong. And if a plugin developper really wants to create those prefixes then it's really easy to create them for yourself by just adding this somewhere in the source file:
```lua
function cPlayer:SendMessageFatal(a_Message) self:SendMessage(cChatColor.Rose .. "[INFO]" .. cChatColor.White .. a_Message) end
-- other functions..
```
